
```{r}
library(ggplot2)
library(dplyr)
library(phyloseq)
library(vegan)
library(tidyverse)

filepath ="C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 5 - Amalies prosjekt - rK intake water in salmon larvea/R-analysis/" 
filepath_figures = paste0(filepath, "Figures/", Sys.Date(), "_")
source(file = "plot_theme.R")
ps = readRDS(file = paste0(filepath, "2023-04-17_phyloseq_without_salmon.RDS"))
sample_data(ps)=sample_data(ps) %>% data.frame() %>% 
  mutate(SampleType2 = case_when(Sample_type == "Intake water"~"AW", 
                                 Sample_type == "Rearing water" ~ "RW", 
                                 T ~Sample_type)) %>%
  mutate(Group = paste0(SampleType2, "_Add-", Selection)) %>%
  mutate(Group = factor(Group, levels = c("Gut_Add-K", 
                                          "Gut_Add-r",
                                          "AW_Add-K", 
                                          "AW_Add-r",
                                          "RW_Add-K",
                                          "RW_Add-r" ))) %>% 
  mutate(DPE = DPE + 7) %>%
  mutate(dph = as.character(DPE)) %>% 
  mutate(dph = factor(dph, levels = c("14", "16", "18", "21", "22"))) %>%
  mutate(Sample_name = case_when(SampleType2 == "Gut"~  
                                   paste0(Flask , "_", Individual), 
                                 SampleType2 == "AW"~  paste0(dph),
                                 SampleType2 == "RW"~  paste0(Flask))) %>% 
  sample_data() 
  
```

```{r}
ps_longer = ps %>% 
  microbiome::transform("compositional") %>%
  phyloseq::otu_table() %>%  t() %>% as.data.frame() %>%
  dplyr::mutate(SampleID = rownames(.)) %>% 
  pivot_longer(-SampleID) 

ps_longer_meta = ps_longer %>% 
  left_join(., microbiome::sample_tibble(ps), by = join_by(SampleID)) %>%
  rename(ASV = "name") %>%
  left_join(., microbiome::tax_tibble(ps) %>% rename(ASV = "FeatureID"), by = join_by(ASV)) %>%
  mutate(Family2 = case_when(substr(Family, 1, 4) == "uncl"~"Unassigned", 
                             T ~ substring(Family, 3))) %>%
  mutate(ASV = paste0("ASV",substring(ASV, 5))) %>%
  mutate(ASV1 = case_when(substring(Genus, 1, 1) == "g" ~ paste0(ASV, " (g:",substring(Genus, 3),")"),
                          substring(Family, 1, 1) == "f" ~ paste0(ASV, " (f:",substring(Family, 3),")"),
                          substring(Order, 1, 1) == "o" ~ paste0(ASV, " (o:",substring(Order, 3),")"),
                          substring(Class, 1, 1) == "c" ~ paste0(ASV, " (c:",substring(Class, 3),")"),
                          substring(Phylum, 1, 1) == "p" ~ paste0(ASV, " (p:",substring(Phylum, 3),")"),
                          TRUE ~ paste0(ASV, " (d:",substring(Domain, 3),")")) ) %>% 
  mutate(value = value * 100)
```
```{r}
write.csv(x = ps_longer_meta,file = paste0(filepath, Sys.Date(), "_composition_ASV_level.csv"))
```

# Rearing and added water

```{r}
ps_meta_family_1percent = ps_longer_meta %>% 
  filter(Sample_type != "Gut") %>% 
  group_by(Sample, Group, Family2) %>%
  #sum of all family abundances in each sample
  summarise(sum = sum(value)) %>%  
  ungroup() %>%
  group_by(Family2) %>%
  summarise(tot_sum = sum(sum), #total abundance all water samples
            max = max(sum)) %>% # max abundance in one sample
  filter(tot_sum>1 | max > 1)
```

```{r}
fam_rw_ad = ps_longer_meta %>% 
  filter(Sample_type!= "Gut", Family2 %in% ps_meta_family_1percent$Family2) %>%
  group_by(Sample, DPE, Family2, Group, Sample_name) %>%
  summarise(fam_abundance = sum(value)) %>%
  ungroup(  ) %>%
  mutate(Family2 = factor(Family2, levels = unique(Family2)[order(fam_abundance, decreasing = F)])) %>% 
  ggplot(aes(y=Sample_name, x = fam_abundance, fill = Family2)) +
  geom_bar(stat = "identity")+ 
  facet_grid(Group~., scales = "free", space = "free", switch = "y") + 
  my.theme  + 
  coord_cartesian(expand = F) + 
  xlab("Relative abundance (%)") + 
  scale_y_discrete(limits=rev) + 
  scale_fill_manual("", values = (col_fam)) + 
  theme(axis.title.y =element_blank() , 
        panel.grid.major.y = element_blank(), 
        legend.position = "bottom", 
        panel.spacing = unit(0.4, "lines")) + 
  guides(fill = guide_legend(ncol = 4, reverse = T))
```

```{r}
fam_rw_ad1_data = ps_longer_meta %>% 
  filter(Sample_type!= "Gut", Family2 %in% ps_meta_family_1percent$Family2) %>%
  group_by(Sample, DPE, Family2, Group, Sample_name) %>%
  summarise(fam_abundance = sum(value)) %>%
  ungroup(  ) %>%
  mutate(Family2 = factor(Family2, levels = unique(Family2)[order(fam_abundance, decreasing = F)])) 
  
fam_rw_ad1 = fam_rw_ad1_data %>%
  ggplot(aes(x=Sample_name, y = fam_abundance, fill = Family2)) +
  geom_bar(stat = "identity")+ 
  facet_grid(~Group, scales = "free", space = "free", switch = "x" ) + 
  my.theme  + 
  coord_cartesian(expand = F) + 
  ylab("Relative abundance (%)") + 
  scale_fill_manual("", values = (col_fam)) + 
  theme(axis.title.x =element_blank() , 
        panel.grid.major.y = element_blank(), 
        legend.position = "bottom", 
        panel.spacing = unit(0.4, "lines")) + 
  guides(fill = guide_legend(ncol = 4, reverse = T))
```
```{r}
write.csv(x = fam_rw_ad1_data,file = paste0(filepath, Sys.Date(), "_composition_family_rwaw.csv"))
```


```{r}
ps_meta_ASV_top20 = ps_longer_meta %>%
  filter(Sample_type != "Gut") %>% 
  group_by(ASV) %>%
  summarise(sum = sum(value)) %>% 
  arrange(desc(sum))
```
```{r}
asv_rw_ad = ps_longer_meta %>% 
  filter(Sample_type!= "Gut", ASV %in% ps_meta_ASV_top20$ASV[1:20]) %>% 
  mutate(ASV1 = factor(ASV1, levels = unique(ASV1)[order(value, decreasing = F)])) %>%
  ggplot(aes(y=Sample_name, x = value, fill = ASV1)) +
  geom_bar(stat = "identity")+ 
  facet_grid(Group~., scales = "free", space = "free", switch = "y") + 
  my.theme  + 
  coord_cartesian(expand = F) + 
  xlab("Relative abundance (%)") + 
  scale_y_discrete(limits=rev) + 
  scale_fill_manual("", values = rev(col)) + 
  theme(axis.title.y =element_blank(), 
        panel.grid.major.y = element_blank(), 
        legend.position = "bottom", 
        panel.spacing = unit(0.4, "lines")) + 
  guides(fill = guide_legend(ncol = 3, reverse = T))
```
```{r}

asv_rw_ad1_data = ps_longer_meta %>% 
  filter(Sample_type!= "Gut", ASV %in% ps_meta_ASV_top20$ASV[1:20]) %>% 
  mutate(ASV1 = factor(ASV1, levels = unique(ASV1)[order(value, decreasing = F)])) 

asv_rw_ad1 = asv_rw_ad1_data %>%  ggplot(aes(x=Sample_name, y = value, fill = ASV1)) +
  geom_bar(stat = "identity")+ 
  facet_grid(~Group, scales = "free", space = "free", switch = "x") + 
  my.theme  + 
  coord_cartesian(expand = F) + 
  ylab("Relative abundance (%)") + 
  scale_fill_manual("", values = rev(col)) + 
  theme(axis.title.x =element_blank(), 
        panel.grid.major.y = element_blank(), 
        legend.position = "bottom", 
        panel.spacing = unit(0.4, "lines")) + 
  guides(fill = guide_legend(ncol = 3, reverse = T))
```

```{r}
write.csv(x = asv_rw_ad1_data,file = paste0(filepath, Sys.Date(), "_composition_ASV_rwaw.csv"))
```


```{r}
# Apply on original plot
asv_rw_ad = addSmallLegend(myPlot = asv_rw_ad, spaceLegend = 0.8,textSize = 10)
fam_rw_ad= addSmallLegend(myPlot = fam_rw_ad, spaceLegend = 0.8,textSize = 10)


asv_rw_ad1 = addSmallLegend(myPlot = asv_rw_ad1, spaceLegend = 0.8,textSize = 10)
fam_rw_ad1= addSmallLegend(myPlot = fam_rw_ad1, spaceLegend = 0.8,textSize = 10)
```
```{r}
ggpubr::ggarrange(fam_rw_ad, asv_rw_ad, labels = c("a)", "b)"),
                  nrow = 2, heights = c(0.45,0.55))

ggpubr::ggarrange(fam_rw_ad1, asv_rw_ad1, labels = c("a)", "b)"),
                  nrow = 2, heights = c(0.45,0.55))   + 
  ggpubr::bgcolor(color = "white")

ggsave(filename = paste0(filepath_figures, "Fig4_composition_aw_rw.png"), 
       width = 180, height = 200, units = "mm")
```

# Gut
```{r}
ps_meta_family_10percent_gut =
ps_longer_meta %>%
  filter(Sample_type == "Gut") %>%
  group_by(Sample, Group, Family2) %>%
  #sum of all family abundances in each sample
  summarise(sum = sum(value)) %>% 
  ungroup() %>%
  group_by(Family2) %>%
  summarise(tot_sum = sum(sum), #total abundance all water samples
            max = max(sum)) %>% # max abundance in one sample
  filter(tot_sum>40 | max > 40)

ps_meta_family_top20 =
ps_longer_meta %>%
  filter(Sample_type == "Gut") %>%
  group_by(Family2) %>%
  #sum of all family abundances in each sample
  summarise(sum = sum(value)) %>% 
  arrange(desc(sum))
```


```{r}
fam_gut_data = ps_longer_meta %>% 
  filter(Sample_type == "Gut", Family2 %in% ps_meta_family_top20$Family2[1:20]) %>%
  group_by(Sample, DPE, Flask, Individual, Strain, Family2, Group, Sample_name) %>%
  summarise(fam_abundance = sum(value)) %>%
  mutate(Family2 = factor(Family2, levels = unique(Family2)[order(fam_abundance, decreasing = F)])) %>% 
  ungroup(  ) %>%
  mutate(Strain = case_when(Strain == "A" ~ "Aquaculture salmon strain", 
                            Strain == "W" ~ "Wiltype salmon strain")) %>% 
  mutate(group2 = paste0(Group, ": ", Strain))

fam_gut = fam_gut_data %>%
  
  ggplot(aes(y=paste0(substring(Flask, 2), "-", Individual), x = fam_abundance, fill = Family2)) +
  geom_bar(stat = "identity")+ 
  facet_wrap(~group2, scales = "free_y" ) + 
  my.theme  + 
  coord_cartesian(expand = F) + 
  xlab("Relative abundance (%)") + 
  scale_fill_manual("", values = rev(col)) + 
  theme(axis.title.y =element_blank()) +  
  theme(panel.grid.major.y = element_blank(), 
        legend.position = "bottom") + 
  guides(fill = guide_legend(ncol = 4))
```

```{r}
ggsave(filename = paste0(filepath_figures, "Fig8_gut_community_composition.png"), 
       width = 180, height = 200, units = "mm") 
```

```{r}
write.csv(x = fam_gut_data,file = paste0(filepath, Sys.Date(), "_composition_family_gut.csv"))
```

#Gut top 200
```{r}
ps_meta_ASV_top20 =
ps_longer_meta %>%
  filter(Sample_type == "Gut") %>%
  group_by(ASV) %>%
  #sum of all family abundances in each sample
  summarise(sum = sum(value)) %>% 
  arrange(desc(sum))
```


```{r}
color = grDevices::colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]
col200 =sample(color, 200)

gut_200_Asvs_data = ps_longer_meta %>% 
  filter(Sample_type == "Gut", ASV %in% ps_meta_ASV_top20$ASV[1:200]) %>%
  group_by(Sample, DPE, Flask, Individual, Strain, Family2, Group, Sample_name) %>%
  mutate(ASV = factor(ASV, levels = unique(ASV)[order(value, decreasing = F)])) %>% 
  ungroup(  ) %>%
  mutate(Strain = case_when(Strain == "A" ~ "Aquaculture salmon strain", 
                            Strain == "W" ~ "Wiltype salmon strain")) %>% 
  mutate(group2 = paste0(Group, ": ", Strain))

  gut_200_Asvs = gut_200_Asvs_data %>%
  ggplot(aes(y=paste0(substring(Flask, 2), "-", Individual), x = value, fill = ASV)) +
  geom_bar(stat = "identity")+ 
  facet_wrap(~group2, scales = "free_y" ) + 
  my.theme  + 
  coord_cartesian(expand = F) + 
  xlab("Relative abundance (%)") + 
  theme(axis.title.y =element_blank()) +  
  theme(panel.grid.major.y = element_blank(), 
        legend.position = "bottom") + 
  scale_fill_manual(values = col200) + 
  guides(fill = guide_legend("", ncol = 11))

gut_200_Asvs1 = addSmallLegend(myPlot = gut_200_Asvs, spaceLegend = 0.7,textSize = 7)

ggsave(gut_200_Asvs1, filename = paste0(filepath_figures, "Suppfig3_top200ASVs.png"), width = 180, height = 200, units = "mm")
```

```{r}
write.csv(x = gut_200_Asvs_data,file = paste0(filepath, Sys.Date(), "_composition_top200ASV_gut.csv"))
```


```{r}
gut_10_Asvs_data = 

ps_longer_meta %>% 
  filter(Sample_type == "Gut", ASV %in% ps_meta_ASV_top20$ASV[1:10]) %>%
  group_by(Sample, DPE, Flask, Individual, Strain, Family2, Group, Sample_name) %>%
  mutate(ASV1 = factor(ASV1, levels = unique(ASV1)[order(value, decreasing = F)])) %>% 
  ungroup(  ) %>%
  mutate(Strain = case_when(Strain == "A" ~ "Aquaculture salmon strain", 
                            Strain == "W" ~ "Wiltype salmon strain")) %>% 
  mutate(group2 = paste0(Group, ": ", Strain))

gut_10_Asvs= gut_10_Asvs_data %>%
  ggplot(aes(y=paste0(substring(Flask, 2), "-", Individual), x = value, fill = ASV1)) +
  geom_bar(stat = "identity")+ 
  facet_wrap(~group2, scales = "free_y" ) + 
  my.theme  + 
  coord_cartesian(expand = F) + 
  xlab("Relative abundance (%)") + 
  theme(axis.title.y =element_blank()) +  
  theme(panel.grid.major.y = element_blank(), 
        legend.position = "bottom") + 
  scale_fill_manual(values = col) + 
  guides(fill = guide_legend("", ncol = 3))

gut_10_Asvs1 = addSmallLegend(myPlot = gut_10_Asvs, spaceLegend = 0.7,textSize = 10)

ggsave(gut_10_Asvs1, filename = paste0(filepath_figures, "Suppfig3_to10ASVs.png"), width = 180, height = 150, units = "mm")
```
```{r}
write.csv(x = gut_10_Asvs_data,file = paste0(filepath, Sys.Date(), "_composition_top10ASV_gut.csv"))
```

# Shared ASVs
```{r}
ps_longer_shared = ps %>% 
  phyloseq::otu_table() %>%  t() %>% as.data.frame() %>%
  dplyr::mutate(SampleID = rownames(.)) %>% 
  pivot_longer(-SampleID) 

ps_longer_meta_shared = ps_longer_shared %>% 
  left_join(., microbiome::sample_tibble(ps), by = join_by(SampleID)) %>%
  rename(ASV = "name") %>%
  left_join(., microbiome::tax_tibble(ps) %>% rename(ASV = "FeatureID"), by = join_by(ASV)) %>%
  mutate(Family2 = case_when(substr(Family, 1, 4) == "uncl"~"Unassigned", 
                             T ~ substring(Family, 3))) %>%
  mutate(ASV = paste0("ASV",substring(ASV, 5))) %>%
  mutate(ASV1 = case_when(substring(Genus, 1, 1) == "g" ~ paste0(ASV, " (g:",substring(Genus, 3),")"),
                          substring(Family, 1, 1) == "f" ~ paste0(ASV, " (f:",substring(Family, 3),")"),
                          substring(Order, 1, 1) == "o" ~ paste0(ASV, " (o:",substring(Order, 3),")"),
                          substring(Class, 1, 1) == "c" ~ paste0(ASV, " (c:",substring(Class, 3),")"),
                          substring(Phylum, 1, 1) == "p" ~ paste0(ASV, " (p:",substring(Phylum, 3),")"),
                          TRUE ~ paste0(ASV, " (d:",substring(Domain, 3),")")) ) 

shared_all = ps_longer_meta_shared %>% 
  select(ASV, value, Group) %>%
  mutate(Group =str_replace_all(Group,pattern = '-',replacement = '_') ) %>%
  group_by(ASV, Group) %>%
  summarise(sum_value = sum(value)) %>%
  pivot_wider(names_from = "Group", values_from = "sum_value")
```


```{r}
shared_gutK = shared_all %>% 
  select(contains("Add_K")) %>% 
  filter(Gut_Add_K>0) %>%
  mutate(shared = case_when(Gut_Add_K>0 & AW_Add_K > 0 & RW_Add_K > 0 ~ "ASVs shared with Aw and Rw",
                            Gut_Add_K>0 & AW_Add_K > 0 & RW_Add_K == 0 ~ "ASVs shared with Aw", 
                            Gut_Add_K>0 & AW_Add_K == 0 & RW_Add_K == 0 ~ "ASVs unique to Gut", 
                            Gut_Add_K>0 & AW_Add_K == 0 & RW_Add_K > 0 ~ "ASVs shared with Rw" )) %>%
  select(ASV, shared, Gut_Add_K) %>%
  ungroup() %>% group_by(shared) %>%
  summarise(sum = sum(Gut_Add_K)) %>%
  mutate(tot = sum(sum), fraction = sum/tot, group = "Gut_Add-K")

shared_gutr = shared_all %>% 
  select(contains("Add_r")) %>%
  filter(Gut_Add_r>0) %>%
  mutate(shared = case_when(Gut_Add_r>0 & AW_Add_r > 0 & RW_Add_r > 0 ~ "ASVs shared with Aw and Rw",
                            Gut_Add_r>0 & AW_Add_r > 0 & RW_Add_r == 0 ~ "ASVs shared with Aw", 
                            Gut_Add_r>0 & AW_Add_r == 0 & RW_Add_r == 0 ~ "ASVs unique to Gut", 
                            Gut_Add_r>0 & AW_Add_r == 0 & RW_Add_r > 0 ~ "ASVs shared with Rw" )) %>%
  select(ASV, shared, Gut_Add_r) %>%
  ungroup() %>% group_by(shared) %>%
  summarise(sum = sum(Gut_Add_r)) %>%
  mutate(tot = sum(sum), fraction = sum/tot, group = "Gut_Add-r")
```
```{r}
bind_rows(shared_gutK, shared_gutr) %>% 
  mutate(shared = factor(shared, levels = unique(shared)[order(fraction, decreasing = F)])) %>%
  ggplot(aes(x=group, y = fraction, fill = shared)) + 
  geom_bar(stat = "identity") + 
  my.theme + 
  coord_cartesian(expand = F) + 
  ylab("Fraction of reads") +
  scale_fill_manual(values = cbPalette[c(6, 1, 2, 3)], "") + 
  ylab("")
```
# Shared sample type
```{r}
shared_all = ps_longer_meta_shared %>% 
  select(ASV, value, SampleType2) %>%
  group_by(ASV, SampleType2) %>%
  summarise(sum_value = sum(value)) %>%
  pivot_wider(names_from = "SampleType2", values_from = "sum_value")

shared_gut = shared_all %>% 
  filter(Gut>0) %>%
  mutate(shared = case_when(Gut>0 & AW > 0 & RW > 0 ~ "ASVs shared with Aw and Rw",
                            Gut>0 & AW > 0 & RW == 0 ~ "ASVs shared with Aw", 
                            Gut>0 & AW == 0 & RW == 0 ~ "ASVs unique to Gut", 
                            Gut>0 & AW == 0 & RW > 0 ~ "ASVs shared with Rw" )) %>%
  select(ASV, shared) 
total_reads_gut = ps_longer_meta_shared %>% 
  filter(SampleType2 == "Gut") %>%
  select(ASV, Group, value) %>%
  group_by(Group) %>%
  summarise(tot_reads = sum(value))
  
fraction_plot = ps_longer_meta_shared %>%
  filter(SampleType2 == "Gut") %>%
  select(ASV, Group, value) %>% 
  left_join(., shared_gut,by = join_by(ASV)) %>%
  group_by(Group, shared) %>% 
  summarise(sum = sum(value)) %>%
  na.omit() %>%
  left_join(.,total_reads_gut) %>% 
  mutate(fraction = sum/tot_reads) %>% 
  mutate(shared = factor(shared, levels = unique(shared)[order(fraction, decreasing = F)])) %>%
  ggplot(aes(x=Group, y = fraction, fill = shared)) + 
  geom_bar(stat = "identity") + 
  my.theme + 
  coord_cartesian(expand = F) + 
  ylab("Fraction of reads") +
  scale_fill_manual(values = cbPalette[c(6, 1, 2, 3)], "") + 
  ylab("")
```

